In [1]:
import numpy as np

In [53]:
# define backpropagation of softmax
def backward1(delta,y):
 # output of softmax node from forward pass
    y_diag = np.diag(y)

    d_inputs = np.outer(y, delta) - np.dot(y_diag, delta)

    return d_inputs

# # define backpropagation of softmax using for loop
def backward2(delta=np.array([1,2,3,4,5])):
    y = np.array([1,2,3,4,5]) # output of softmax node from forward pass

    jacobian_matrix = np.zeros((y.shape[0], y.shape[0]))
    for i in range(y.shape[0]):
        for j in range(y.shape[0]):
            if i == j:
                jacobian_matrix[i][j] = y[i] * (1 - y[j])
            else:
                jacobian_matrix[i][j] = -y[i] * y[j]
    return np.dot(delta, jacobian_matrix)

def backward3(delta=np.array([1,2,3,4,5])):
    y = np.array([1,2,3,4,5]) # output of softmax node from forward pass

    # repeat y n times to form a 2d array
    y1 = np.tile(y, (y.shape[0], 1)).T
    # 5x5 identity matrix
    i = np.identity(y.shape[0])
    # repeat y n times to form a 2d array
    y2 = np.tile(y, (y.shape[0], 1))

    jacobian_matrix = y1 * (i - y2)
    return np.dot(delta, jacobian_matrix)



In [54]:
def backward(delta,y):
    # repeat y n times to form a 2d array
    y1 = np.tile(y, (y.shape[0], 1)).T
    # 5x5 identity matrix
    i = np.identity(y.shape[0])
    # repeat y n times to form a 2d array
    y2 = np.tile(y, (y.shape[0], 1))

    jacobian_matrix = y1 * (i - y2)
    return np.dot(delta, jacobian_matrix)

def batch_backward(delta,y):
    grads = np.zeros((y.shape[0], y.shape[1]))
    for i in range(len(delta)):
        d_inputs = backward(delta[i],y[i])
        grads[i] = d_inputs

    return grads

In [ ]:
class CrossEntropy(Node):
    '''
    CrossEntropy loss function
    '''
    def __init__(self):
        super(CrossEntropy, self).__init__('cross_entropy', [])

    def forward(self, x, l):
        '''
        Implement this part
        '''
        if x.ndim == 1:
            l = l.reshape(1,l.size)
            x = x.reshape(1,x.size)
            
        # 监督数据是one-hot-vector的情况下，转换为正确解标签的索引
        if l.size == x.size:
            l = l.argmax(axis=1)
                
        batch_size = x.shape[0]
        self.x = x
        self.l = l
        return -np.sum(np.log(x[np.arange(batch_size), l] + 1e-7)) / batch_size
    
    def backward(self, delta=1):
        '''
        Implement this part
        '''
        # implement cross entropy backward here
        batch_size = self.x.shape[0]
        grad = np.zeros_like(self.x)
        grad[np.arange(batch_size), self.l] = -1 / (self.x[np.arange(batch_size), self.l] + 1e-7)
        return delta * grad / batch_size

In [56]:
backward(delta=np.array([[1,2,3,4,5]]),y=np.array([[1,2,3,4,5]]))
backward1(delta=np.array([[1,2,3,4,5]]),y=np.array([[1,2,3,4,5]]))

array([[   0.,  -55., -110., -165., -220.]])

In [46]:
batch_backward(delta=np.array([[1,2,3,4,5], [1,2,3,4,5]]),
               y=np.array([[1,2,3,4,5], [1,1,1,1,1]]))

array([[ -54., -106., -156., -204., -250.],
       [ -14.,  -13.,  -12.,  -11.,  -10.]])

In [61]:
# use np.tile() to repeat a 1d array n times to form a 2d array
# https://stackoverflow.com/questions/34226400/what-is-the-np-outer-function-in-numpy
# example
a = np.array([1, 2, 3])
print(np.tile(a, (3, 1)).T,end='\n\n')
print(np.tile(a, (3, 1)))



[[1 1 1]
 [2 2 2]
 [3 3 3]]

[[1 2 3]
 [1 2 3]
 [1 2 3]]
